global:
  scrape_interval: 7s

scrape_configs:
  - job_name: "scraper"
    static_configs:
      - targets: [ "0.0.0.0:9100" ]
  - job_name: "asp_scraper"
    static_configs:
      - targets: [ "0.0.0.0:5000" ]
  - job_name: "docker"
    static_configs:
      - targets: [ "0.0.0.0:9323" ]
